version: 'latest'

services:
  database:
    image: "postgres:latest"
    ports:
      - "5431:5432"  
    environment:
      POSTGRES_USER: "Go-crm"
      POSTGRES_PASSWORD: "G0-Supply-C3RM-458"
      POSTGRES_DB: "go-crm"
    restart: "always"  # Moved out of environment section